### ISSUE TITLE
Question about plugin consumption.

### ISSUE THREAD

**Issue by patv2learn** [dranger003/WTSPlugin1#2]
Hello @dranger003, 

Thank you for your last update in WriteFile, it is working perfect. I have used same logic for ReadFile and that is working perfect too, but here I have one other question. I am not sure if you can help / suggest something on it.

I have this plugin dll register on client computer but if I have a other console / winform application running on client computer which needs to read data coming from server or send data back to server, how this is going to work?

In my case, I have server application send a IP address to local application and local application listen that IP address to catch any incoming data and send that back to server application.

I have try to look for forum but could not find much in c# doing such task and since you already worked on this part and if you have any suggestion that would be a great help.

Thanks,
Pat.

**Comment by dranger003** [comment]
You will need to use RPC between your client DLL and your client Console/WinForm application. Technologies I used for this purpose before are C# COM Client/Server or .NET Remoting. You could also use a third party library like Halibut (https://github.com/OctopusDeploy/Halibut).

You may also simplify your life by spawning the Console/WinForm application from within the client DLL (i.e. IWTSPlugin.Initialize) this way there is no need to communicate via RPC and you also ensure your client Console/WinForm will always be running at the same time as the client DLL.

**Comment by patv2learn** [comment]
Thank you very much for your suggestion. I will check with possible approach I can move forward.

**Comment by patv2learn** [comment]
One more question on same line for server end @dranger003, how dose server application get the notification about data received and it has to trigger ReadFile? 

I can see on client dll you have IWTSListener object something like that on server too?

Thanks.

**Comment by dranger003** [comment]
You could call ReadFile and check if data is available periodically using GetOverlappedResult.
